def versionTag = "v${env.BUILD_NUMBER}"
pipeline {
  agent {
    ecs {
      inheritFrom 'plugin-updates'
    }
  }

  stages {
    stage('Test') {
      steps {
        checkout scm
        sh 'plugin-updates'
        sh 'git status'
        sh "git checkout -b plugin-updates-${versionTag}"
        sh 'git add  docker/plugins.txt'
        sh "git config --global user.email tna-digital-archiving-jenkins@nationalarchives.gov.uk"
        sh "git config --global user.name tna-digital-archiving-jenkins"
        sh "git commit -m 'Update plugins'"
        sshagent(['github-jenkins']) {
          sh "git push -u origin plugin-updates-${versionTag}"
        }
      }
    }
  }
}
